creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    age:
      - age1yubikey1qva2uw9dw6cq5me0q4k3j6ada4ul0qpe9ej2kd8d629ca67ta606z43k9ws
      - age1yubikey1qf8eflg3zhjpsj24730l7cn02wnq4ze7jnz629d4kpal5hfca6hyj04mlxz
      - age15gmh8l0vd02ccqdper4ljz0sqd5ljm8s2qdetxfseautagtp6phqg0z5hj
